"""Initial migration

Revision ID: 636a7f2ed280
Revises: 
Create Date: 2026-01-17 18:04:56.476293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '636a7f2ed280'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('django_content_type')
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('auth_user_username_6821ab7c_like'), postgresql_ops={'username': 'varchar_pattern_ops'})

    op.drop_table('auth_user')
    with op.batch_alter_table('auth_user_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('auth_user_groups_group_id_97559544'))
        batch_op.drop_index(batch_op.f('auth_user_groups_user_id_6a12ed8b'))

    op.drop_table('auth_user_groups')
    with op.batch_alter_table('django_admin_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('django_admin_log_content_type_id_c4bce8eb'))
        batch_op.drop_index(batch_op.f('django_admin_log_user_id_c564eba6'))

    op.drop_table('django_admin_log')
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('auth_group_name_a6ea08ec_like'), postgresql_ops={'name': 'varchar_pattern_ops'})

    op.drop_table('auth_group')
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('auth_permission_content_type_id_2f476e4b'))

    op.drop_table('auth_permission')
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('auth_group_permissions_group_id_b120cbf9'))
        batch_op.drop_index(batch_op.f('auth_group_permissions_permission_id_84c5c92e'))

    op.drop_table('auth_group_permissions')
    with op.batch_alter_table('auth_user_user_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('auth_user_user_permissions_permission_id_1fbb5f2c'))
        batch_op.drop_index(batch_op.f('auth_user_user_permissions_user_id_a95ead1b'))

    op.drop_table('auth_user_user_permissions')
    op.drop_table('django_migrations')
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('django_session_expire_date_a5c62663'))
        batch_op.drop_index(batch_op.f('django_session_session_key_c0390e0f_like'), postgresql_ops={'session_key': 'varchar_pattern_ops'})

    op.drop_table('django_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name=op.f('django_session_pkey'))
    )
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('django_session_session_key_c0390e0f_like'), ['session_key'], unique=False, postgresql_ops={'session_key': 'varchar_pattern_ops'})
        batch_op.create_index(batch_op.f('django_session_expire_date_a5c62663'), ['expire_date'], unique=False)

    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_migrations_pkey'))
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_user_user_permissions_pkey')),
    sa.UniqueConstraint('user_id', 'permission_id', name=op.f('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('auth_user_user_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('auth_user_user_permissions_user_id_a95ead1b'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('auth_user_user_permissions_permission_id_1fbb5f2c'), ['permission_id'], unique=False)

    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_permissions_pkey')),
    sa.UniqueConstraint('group_id', 'permission_id', name=op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('auth_group_permissions_permission_id_84c5c92e'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('auth_group_permissions_group_id_b120cbf9'), ['group_id'], unique=False)

    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('auth_permission_content_type_id_2f476e4b_fk_django_co'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_permission_pkey')),
    sa.UniqueConstraint('content_type_id', 'codename', name=op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('auth_permission_content_type_id_2f476e4b'), ['content_type_id'], unique=False)

    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_pkey')),
    sa.UniqueConstraint('name', name=op.f('auth_group_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('auth_group_name_a6ea08ec_like'), ['name'], unique=False, postgresql_ops={'name': 'varchar_pattern_ops'})

    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name=op.f('django_admin_log_action_flag_check')),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('django_admin_log_content_type_id_c4bce8eb_fk_django_co'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('django_admin_log_user_id_c564eba6_fk_auth_user_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('django_admin_log_pkey'))
    )
    with op.batch_alter_table('django_admin_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('django_admin_log_user_id_c564eba6'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('django_admin_log_content_type_id_c4bce8eb'), ['content_type_id'], unique=False)

    op.create_table('auth_user_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_user_groups_group_id_97559544_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('auth_user_groups_user_id_6a12ed8b_fk_auth_user_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_user_groups_pkey')),
    sa.UniqueConstraint('user_id', 'group_id', name=op.f('auth_user_groups_user_id_group_id_94350c0c_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('auth_user_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('auth_user_groups_user_id_6a12ed8b'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('auth_user_groups_group_id_97559544'), ['group_id'], unique=False)

    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_user_pkey')),
    sa.UniqueConstraint('username', name=op.f('auth_user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('auth_user_username_6821ab7c_like'), ['username'], unique=False, postgresql_ops={'username': 'varchar_pattern_ops'})

    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_content_type_pkey')),
    sa.UniqueConstraint('app_label', 'model', name=op.f('django_content_type_app_label_model_76bd3d3b_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
